spring.application.name=FFsmartBackend
server.port=5000
app.jwt.expiration-ms=3600000  
app.jwt.cookie-name=jwt       
app.jwt.secret=eSzHkvjEhLIGZTDMChar69OtQjnqF7cbDtW7KPWUVcY=
# spring.data.mongodb.uri=mongodb+srv://BWT:BWTPASSWORD@cluster0.ndd7r.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.uri=mongodb+srv://BWT:gL1S0uhuNtKaMX5R@cluster0.ndd7r.mongodb.net/ffsmart-db